### ISSUE TITLE
Updated all React components to be .jsx instead of .js

### ISSUE THREAD

**Issue by joelvarty** [agility/agility-gatsby-starter#37]
Every react component should be a jsx file.

Also, update the dynamic module component loading to detect EITHER a .js or a .jsx file so folks can use either.

**Comment by joelvarty** [comment]
@joshua-isaac This would be an awesome update to put in!

**Comment by joshua-isaac** [comment]
@joelvarty adding to my to-do list!

**Comment by joshua-isaac** [comment]
done!
