### ISSUE TITLE
Cannot query field "agilityGlobalHeader" on type "Query".

### ISSUE THREAD

**Issue by SabbeRubbish** [agility/agility-gatsby-starter#39]
Started by cloning https://github.com/agility/agility-gatsby-starter.git and filled in config but got errors all over the place while building.
Connection is succesful, as I can see my pages in the GraphQL explorer, but:

**_success open and validate gatsby-configs - 0.029s
success load plugins - 1.033s
success onPreInit - 0.003s
success initialize cache - 0.014s
success copy gatsby files - 0.778s
success onPreBootstrap - 0.015s
success createSchemaCustomization - 0.005s
AgilityCMS => Source Nodes Started (development)...
AgilityCMS => Touched 0 nodes
AgilityCMS => Starting Sync for en-us - preview mode.
AgilityCMS => Content Sync returned 5 item(s).
AgilityCMS => Page Sync returned 1 item(s).
AgilityCMS => Updating Sitemap channel website in en-us
AgilityCMS => URL Redirections Updated and Saved
AgilityCMS => Completed Sync for en-us - preview mode.
AgilityCMS => Creating sitemap nodes...
AgilityCMS => Source Nodes Completed.
success source and transform nodes - 1.011s
warn `createResolvers` passed resolvers for type `agilityPost` that doesn't exist in the schema. Use `createTypes` to
success building schema - 0.488s
AgilityCMS => Create Pages Started...
AgilityCMS => Homepage requests to /home will redirect to '/'
AgilityCMS => 1 pages created from website in en-us
success createPages - 0.023s
success createPagesStatefully - 0.031s
success onPreExtractQueries - 0.002s
success update schema - 0.036s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "agilityGlobalHeader" on type "Query".

If you don't expect "agilityGlobalHeader" to exist on the type "Query" it is most likely a typo.
However, if you expect "agilityGlobalHeader" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "agilityGlobalHeader" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src\components\GlobalHeader.js:10:4

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allAgilityPost" on type "Query".

If you don't expect "allAgilityPost" to exist on the type "Query" it is most likely a typo.
However, if you expect "allAgilityPost" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allAgilityPost" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src\modules\PostsListing.js:12:13

failed extract queries from components - 0.301s
success write out requires - 0.051s
warn Module Error (from ./node_modules/eslint-loader/index.js):
success onPostBootstrap - 0.001s
D:\Users\smindreau\Source\repos\GatsbyTest\agility-gatsby-starter\src\modules\PostsListing.js
  12:13  error  Cannot query field "allAgilityPost" on type "Query". Did you mean "allAgilitypage", "allAgilitystate",
"allAgilityitem", "agilitypage", or "agilitystate"?  graphql/template-strings
success run queries - 0.051s - 3/3 58.34/s
✖ 1 problem (1 error, 0 warnings)s outdated. Please run:

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed_**

**Comment by joelvarty** [comment]
The gatsby starter is looking for the content that is pre-loaded in the "Blog With Gatsby" starter (https://agilitycms.com/starters/blog-with-gatsby) 

Is that the starter that your instance is based on?

**Comment by SabbeRubbish** [comment]
Hi Joel,

Not it's not, that is probably my problem, that I don't have a GlobalHeader model in Agility.
Thanks for the insight.
